language: python
python:
    - "3.6"
before_install:
#    - pip install -U pytest
    - pip install pytest pytest-cov
    - pip install coveralls

# Are there any other dependencies or required packages before testing?
# For example, something like:
#    - pip install -r requirements.txt

script:
    - pytest
after_success:
    - coveralls
