language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - rm ./requirements.txt
    - pip install codecov

script:
    - pytest --cov=./

after_success:
    - codecov